name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      
  
          

      - name: Install SFDX CLI and sfdx-git-delta plugin
        run: |
          npm install -g sfdx-cli@latest
          echo "y" | npm install  -g sfdx-git-delta@latest

      - name: Create JWT Key File
        run: |
          echo "${{ secrets.JWT_KEYFILE }}" | tr -d '\r' > server.key
          chmod 600 server.key

      - name: 'Authentification Salesforce'
        run: |
          sfdx force:auth:jwt:grant \
          --client-id ${{ secrets.CLIENT_ID }} \
          --jwt-key-file server.key \
          --username ${{ secrets.SF_USERNAME }} \
          --instance-url https://login.salesforce.com

      - name: 'Generate metadata delta pull request'
        run: |
          mkdir -p .temp
          sfdx sgd:source:delta \
            --from HEAD~1 \
            --to HEAD \
            --output .temp

      - name: 'Déployer les métadonnées sur la branch main'
        if: github.ref == 'refs/heads/main'
        run: |
          sfdx force:mdapi:deploy \
            -d .temp \
            --targetusername ${{ secrets.SF_USERNAME }} \
            --testlevel RunLocalTests
